#comment Werror because of ocr-affinity.h
#CFLAGS=-O3 -g -Werror -Iinc -I. -I../../inc -c
INCS=-I./inc -I../../inc
CFLAGS=-O3 -g $(INCS) -c
OCR_FLAGS=-L${OCR_INSTALL}/lib -I${OCR_INSTALL}/include -locr -lpthread -lm

ifndef OCR_INSTALL
$(error OCR_INSTALL not set)
endif

ifndef OCR_CONFIG
OCR_CONFIG=${OCR_INSTALL}/config/default.cfg
$(warning OCR_CONFIG not set, defaulting to ${OCR_CONFIG})
endif

OCR_RUN_FLAGS=-ocr:cfg ${OCR_CONFIG}

DEPS=helper.c

all-test: compile run

compile:
	gcc $(CFLAGS) $(CUSTOM_BOUNDS) $(PROG).c -o $(PROG).o
	gcc $(INCS) -g -o $(PROG) $(DEPS) $(PROG).o $(OCR_FLAGS)

run:
	./$(PROG) $(OCR_RUN_FLAGS)

clean:
	-rm -Rf *.o $(PROG)
